import Foundation

// Charades: actions, jobs, scenes and sayings that act out well
enum ActWordsEN {

    static let pool: [String] = [
        "brushing teeth", "washing your face", "sleeping", "yawning",
        "running", "swimming", "taking a photo", "making a phone call",
        "driving", "riding a bike", "playing piano", "playing drums",
        "singing", "dancing", "sweeping", "cooking",
        "fishing", "weightlifting", "basketball", "soccer",
        "ping pong", "boxing", "yoga", "saluting",
        "clapping", "waving", "gorilla", "rabbit",
        "frog", "crab", "snake", "chicken",
        "duck", "eagle", "monkey", "elephant",
        "penguin", "T-Rex", "cat", "dog",
        "barber", "chef", "doctor", "nurse",
        "traffic cop", "firefighter", "photographer", "news anchor",
        "teacher", "delivery driver", "waiter", "construction worker",
        "astronaut", "magician", "ninja", "detective",
        "zombie", "mummy", "robot", "ballerina",
        "surfer", "DJ", "cheerleader", "referee",
        "lifeguard", "opera singer", "mime", "juggler",
        "tightrope walker", "air guitar", "snowball fight", "opening a present",
        "blowing out candles", "walking the dog", "changing a diaper", "mowing the lawn",
        "shoveling snow", "grocery shopping", "taking a selfie", "texting while walking",
        "the Titanic bow scene", "a Rocky training montage", "Spider-Man shooting webs", "Darth Vader breathing",
        "Godzilla attacking a city", "the moonwalk", "the floss dance", "winning the lottery",
        "stepping on a Lego", "brain freeze", "food coma", "stage fright",
        "a job interview", "a first date", "a marriage proposal", "getting a parking ticket",
        "missing the bus", "locked out of the house", "a karaoke fail", "burning dinner",
        "walking on hot sand", "a paper cut", "slipping on a banana peel", "riding a mechanical bull",
        "caught in the rain", "a haunted house tour", "a roller coaster drop", "turbulence on a plane",
        "milking a cow", "birdwatching", "using a metal detector", "photobombing",
        "assembling flat-pack furniture", "tying shoelaces", "buttoning a shirt", "zipping a jacket",
        "putting on makeup", "shaving", "combing hair", "blow-drying hair",
        "flossing", "gargling", "washing dishes", "folding laundry",
        "ironing a shirt", "vacuuming", "dusting shelves", "making the bed",
        "watering plants", "feeding a cat", "walking a tightrope", "threading a needle",
        "sewing a button", "knitting a scarf", "wrapping a gift", "blowing up a balloon",
        "popping bubble wrap", "lighting a candle", "stirring a pot", "flipping a pancake",
        "kneading dough", "cracking an egg", "peeling a banana", "squeezing a lemon",
        "opening a jar", "pouring tea", "drinking through a straw", "eating spaghetti",
        "eating spicy food", "eating ice cream", "chewing gum", "blowing a bubble",
        "sipping soup", "carving a turkey", "toasting with a glass", "setting the table",
        "serving a customer", "counting money", "typing fast", "answering the phone",
        "taking notes", "giving a speech", "raising a hand", "shaking hands",
        "high five", "thumbs up", "crossing fingers", "shrugging",
        "nodding", "face palm", "tiptoeing", "limping",
        "marching", "skipping", "crawling", "somersault",
        "cartwheel", "handstand", "push-ups", "sit-ups",
        "squats", "stretching", "jogging in place", "jumping jacks",
        "lifting a heavy box", "pushing a shopping cart", "pulling a rope", "climbing a ladder",
        "climbing stairs", "riding an escalator", "hailing a taxi", "parallel parking",
        "buckling a seatbelt", "pumping gas", "changing a tire", "checking a map",
        "reading a menu", "ordering coffee", "paying with a card", "waiting for an elevator",
        "knocking on a door", "ringing a doorbell", "locking a door", "searching for keys",
        "carrying groceries", "opening an umbrella", "brushing off snow", "shivering in the cold",
        "fanning yourself", "sweating", "sneezing", "coughing",
        "snoring", "hiccuping", "tickling", "scratching an itch",
        "rubbing your eyes", "blowing your nose", "taking medicine", "getting a shot",
        "taking your temperature", "bandaging a finger", "rocking a baby", "burping a baby",
        "pushing a stroller", "playing peekaboo", "reading a bedtime story", "teaching a class",
        "raising your hand in class", "taking a test", "cheating on a test", "falling asleep in class",
        "graduating", "giving a toast", "proposing", "cutting a wedding cake",
        "throwing a bouquet", "unwrapping a present", "taking a group photo", "posing for a photo",
        "video calling", "scrolling on a phone", "taking a screenshot", "playing video games",
        "strumming a guitar", "conducting an orchestra", "playing violin", "playing flute",
        "beatboxing", "lip syncing", "air drumming", "break dancing",
        "ballet", "tap dancing", "line dancing", "juggling",
        "card trick", "pulling a rabbit from a hat", "sword swallowing", "mime in a box",
        "balancing a plate", "hula hooping", "spinning a basketball", "dribbling",
        "shooting a free throw", "serving a tennis ball", "swinging a golf club", "batting",
        "bowling", "pitching", "goalkeeping", "head-butting a ball",
        "sprinting", "hurdling", "long jump", "high jump",
        "shot put", "javelin throw", "rowing", "paddling a kayak",
        "water skiing", "snorkeling", "ice skating", "snowboarding",
        "sledding", "horseback riding", "shearing a sheep", "herding sheep",
        "plowing a field", "planting seeds", "harvesting wheat", "picking apples",
        "chopping wood", "sawing a plank", "hammering a nail", "drilling a hole",
        "painting a wall", "laying bricks", "welding", "fixing a pipe",
        "mopping a floor", "directing traffic", "blowing a whistle", "standing guard",
        "marching in a parade", "firing a cannon", "rowing a dragon boat", "lion dance",
        "kung fu", "tai chi", "karate chop", "sumo wrestling",
        "fencing", "archery", "target shooting", "sword fighting",
        "boxing match", "arm wrestling", "thumb war", "rock paper scissors",
        "staring contest", "hide and seek", "freeze tag", "musical chairs",
        "limbo", "piñata", "bobbing for apples", "trick or treating",
        "carving a pumpkin", "building a sandcastle", "flying a drone", "metal detecting",
        "bird watching", "stargazing", "fortune telling", "palm reading",
        "meditating", "praying", "bowing", "zombie walk",
        "robot dance", "sleepwalking", "being a statue", "mirror game",
        "donkey", "turkey", "tiger", "lion",
        "zebra", "hippo", "rhino", "panda",
        "koala", "camel", "llama", "alpaca",
        "walrus", "seal", "otter", "beaver",
        "badger", "hamster", "parrot", "peacock",
        "pelican", "flamingo", "ostrich", "puffin",
        "seagull", "sparrow", "swallow", "woodpecker",
        "owl", "falcon", "vulture", "dove",
        "goose", "duckling", "piglet", "puppy",
        "kitten", "bunny", "squirrel", "hedgehog",
        "mole", "bat", "toad", "turtle",
        "tortoise", "lizard", "gecko", "iguana",
        "cobra", "python", "crocodile", "dolphin",
        "whale", "shark", "starfish", "seahorse",
        "octopus", "snail", "spider", "beetle",
        "ladybug", "dragonfly", "grasshopper", "cricket",
        "mosquito", "jumping", "baking", "painting",
        "reading", "writing", "laughing", "crying",
        "shouting", "whispering", "walking", "climbing",
        "flying", "sailing", "skating", "skiing",
        "surfing", "camping", "shopping", "cleaning",
        "washing", "knitting", "mommy", "daddy",
        "grandma", "grandpa", "brother", "sister",
        "uncle", "auntie", "cousin", "neighbor",
        "farmer", "pilot", "sailor", "soldier",
        "painter", "singer", "dancer", "baker",
        "driver", "guard", "king", "queen",
        "prince", "princess", "wizard", "witch",
        "giant", "dragon", "ghost", "monster",
        "angel", "fairy", "taking a shower", "flying a kite",
        "building a snowman", "jump rope", "tug of war", "scuba diving",
        "rock climbing", "bungee jumping", "wedding", "graduation",
        "traffic jam", "waiting in line", "daydreaming", "sunburn",
        "mermaid", "unicorn", "alien", "vacuum cleaner",
        "sandwich", "Statue of Liberty", "Eiffel Tower", "the pyramids",
        "Big Ben", "Golden Gate Bridge", "Mount Rushmore", "treadmill",
        "tangled headphones", "police officer", "lawyer", "dentist",
        "mail carrier", "skydiving", "karaoke", "escape room",
        "online shopping", "food delivery", "binge-watching", "video call",
        "the Super Bowl", "the World Cup", "the Olympics", "a marathon",
        "Spider-Man", "Batman", "Superman", "Iron Man",
        "Pikachu", "SpongeBob", "Mickey Mouse", "Santa Claus",
        "Godzilla", "King Kong", "Mario", "Sonic the Hedgehog",
        "Popeye", "Winnie the Pooh", "Scooby-Doo", "Frosty the Snowman",
        "Little Red Riding Hood", "The Three Little Pigs", "The Boy Who Cried Wolf", "Jack and the Beanstalk",
        "Humpty Dumpty", "The Tortoise and the Hare", "Puss in Boots", "Christmas",
        "Halloween", "Thanksgiving", "New Year's Eve", "Valentine's Day",
        "birthday party", "road trip", "going to the movies", "working out",
        "doing laundry", "beach vacation", "Titanic", "Rocky",
        "Top Gun", "Indiana Jones", "Ghostbusters", "Men in Black",
        "The Terminator", "E.T.", "Jumanji", "Forrest Gump",
        "The Matrix", "Star Wars", "Harry Potter", "Jurassic Park",
        "The Avengers", "Pirates of the Caribbean",
    ]
}
