import Foundation

// Say & Guess: the fastest game to guess, so it gets the biggest pool
enum DescribeWordsEN {

    static let pool: [String] = [
        "pizza", "birthday cake", "umbrella", "elephant",
        "giraffe", "doctor", "teacher", "firefighter",
        "basketball", "soccer", "swimming", "dancing",
        "rainbow", "snowman", "beach", "library",
        "airport", "ice cream", "hamburger", "popcorn",
        "laptop", "headphones", "toothbrush", "backpack",
        "roller coaster", "campfire", "treehouse", "skateboard",
        "sunglasses", "watermelon", "penguin", "dolphin",
        "kangaroo", "vampire", "superhero", "pirate",
        "robot", "astronaut", "ninja", "mermaid",
        "piece of cake", "break a leg", "couch potato", "road trip",
        "brain freeze", "photobomb", "binge-watching", "spring cleaning",
        "midnight snack", "dad joke", "group chat", "selfie stick",
        "escape room", "food truck", "garage sale", "happy hour",
        "jet lag", "karaoke night", "lemonade stand", "movie marathon",
        "road rage", "secret handshake", "slam dunk", "snow day",
        "spoiler alert", "surprise party", "talent show", "time capsule",
        "trick or treat", "tug of war", "white lie", "wild goose chase",
        "sweet tooth", "cold feet", "curveball", "elephant in the room",
        "food coma", "early bird", "night owl", "bucket list",
        "Albert Einstein", "Sherlock Holmes", "Harry Potter", "Darth Vader",
        "Cinderella", "Batman", "Spider-Man", "the Mona Lisa",
        "William Shakespeare", "Leonardo da Vinci", "Isaac Newton", "Cleopatra",
        "Santa Claus", "the Tooth Fairy", "Bigfoot", "the Loch Ness Monster",
        "once in a blue moon", "the ball is in your court", "beat around the bush", "bite the bullet",
        "spill the beans", "under the weather", "hit the hay", "burn the midnight oil",
        "cost an arm and a leg", "the last straw", "let the cat out of the bag", "raining cats and dogs",
        "barking up the wrong tree", "a blessing in disguise", "the tip of the iceberg", "throw in the towel",
        "walk on eggshells", "devil's advocate", "the whole nine yards", "jump on the bandwagon",
        "cut to the chase", "go the extra mile", "on cloud nine", "up in the air",
        "alarm clock", "traffic light", "speed bump", "parking meter",
        "subway station", "airport security", "baggage claim", "boarding pass",
        "window seat", "carry-on bag", "hotel lobby", "room service",
        "swimming pool", "water slide", "ski lift", "hiking trail",
        "mountain summit", "sunrise", "sunset", "full moon",
        "solar eclipse", "shooting star", "northern lights", "thunderstorm",
        "heat wave", "snowstorm", "flood", "earthquake",
        "tornado", "drought", "recycling", "solar panel",
        "wind turbine", "electric car", "charging station", "self-checkout",
        "loyalty card", "coupon", "warranty", "receipt",
        "refund", "delivery driver", "takeout order", "leftovers",
        "grocery list", "farmers market", "food festival", "street food",
        "buffet", "picnic", "barbecue", "potluck",
        "housewarming", "baby shower", "family reunion", "class reunion",
        "office party", "team building", "performance review", "promotion",
        "resignation letter", "first paycheck", "overtime", "lunch break",
        "water cooler chat", "commute", "carpool", "rush hour",
        "detour", "road closure", "speeding ticket", "driving test",
        "learner's permit", "parallel parking", "flat tire", "jump start",
        "car wash", "oil change", "insurance claim", "rent",
        "mortgage", "utility bill", "savings account", "piggy bank",
        "allowance", "tip jar", "thrift store", "hand-me-down",
        "online auction", "package delivery", "lost luggage", "missed flight",
        "layover", "souvenir", "guided tour", "travel diary",
        "postcard", "pen pal", "group project", "pop quiz",
        "report card", "detention", "school play", "field trip",
        "science fair", "spelling bee", "prom", "yearbook",
        "summer camp", "sleepover", "treasure hunt", "scavenger hunt",
        "board game night", "open mic", "stand-up comedy", "magic show",
        "circus", "parade", "fireworks show", "carnival ride",
        "haunted house", "costume party", "new year's resolution", "housework",
        "babysitting", "dog walking", "pet adoption", "vet visit",
        "grooming", "first day of school", "first job", "first date",
        "long distance relationship", "blind date", "double date", "anniversary",
        "honeymoon", "retirement", "The Lion King", "Frozen",
        "Toy Story", "Finding Nemo", "Snow White", "The Little Mermaid",
        "Sleeping Beauty", "Peter Pan", "Shrek", "Kung Fu Panda",
        "Ice Age", "Minions", "Zootopia", "Cars",
        "Superman", "Iron Man", "Titanic", "Aladdin",
        "Mulan", "Moana", "Tangled", "Bambi",
        "Dumbo", "Pinocchio", "101 Dalmatians", "The Jungle Book",
        "Madagascar", "Happy Feet", "Rio", "Big Hero 6",
        "Wreck-It Ralph", "Alice in Wonderland", "The Croods", "Trolls",
        "Sing", "Turning Red", "Luca", "Soul",
        "The Grinch", "Home Alone", "SpongeBob", "Tom and Jerry",
        "Mickey Mouse", "Pikachu", "Winnie the Pooh", "Scooby-Doo",
        "Bugs Bunny", "Popeye", "Garfield", "Snoopy",
        "The Simpsons", "Hello Kitty", "Barbie", "Mario",
        "Sonic the Hedgehog", "Donkey Kong", "Pac-Man", "Angry Birds",
        "Minecraft", "Doraemon", "Astro Boy", "Godzilla",
        "King Kong", "Frosty the Snowman", "The Three Little Pigs", "Little Red Riding Hood",
        "The Ugly Duckling", "The Tortoise and the Hare", "Goldilocks and the Three Bears", "Jack and the Beanstalk",
        "Hansel and Gretel", "The Boy Who Cried Wolf", "The Emperor's New Clothes", "Humpty Dumpty",
        "The Gingerbread Man", "Puss in Boots", "break the ice", "when pigs fly",
        "time flies", "over the moon", "hot dog", "bookworm",
        "copycat", "eagle eye", "busy as a bee", "in hot water",
        "head in the clouds", "green thumb", "cat nap", "big fish",
        "top dog", "black sheep", "heart of gold", "hot potato",
        "snail mail", "lovebirds", "fish out of water", "sitting duck",
        "cash cow", "french fries", "sushi", "tacos",
        "spaghetti", "pancakes", "donut", "cupcake",
        "pineapple", "strawberry", "peanut butter and jelly", "fish and chips",
        "chicken soup", "apple pie", "hot chocolate", "coffee",
        "milkshake", "bacon and eggs", "grilled cheese", "corn on the cob",
        "panda", "butterfly", "octopus", "unicorn",
        "dinosaur", "hedgehog", "volcano", "sunflower",
        "desert island", "Christmas", "Halloween", "Thanksgiving",
        "New Year's Eve", "Valentine's Day", "birthday party", "camping",
        "going to the movies", "grocery shopping", "working out", "walking the dog",
        "doing laundry", "traffic jam", "beach vacation", "Star Wars",
        "Jurassic Park", "Pirates of the Caribbean", "The Avengers", "The Lord of the Rings",
        "Avatar", "Back to the Future", "The Matrix", "Jaws",
        "Ghostbusters", "Men in Black", "The Wizard of Oz", "Beauty and the Beast",
        "Up", "Ratatouille", "Monsters, Inc.", "Inside Out",
        "Coco", "Encanto", "The Incredibles", "Wall-E",
        "Despicable Me", "Rocky", "Top Gun", "Indiana Jones",
        "The Mummy", "Mission: Impossible", "The Hunger Games", "The Terminator",
        "Alien", "E.T.", "Jumanji", "Forrest Gump",
        "The Martian", "Black Panther", "Wonder Woman", "Friends",
        "Stranger Things", "Game of Thrones", "Breaking Bad", "The Office",
        "Sherlock", "Family Guy", "Squid Game", "Black Mirror",
        "The Walking Dead", "Doctor Who", "The Crown", "The Mandalorian",
        "Wednesday", "The Big Bang Theory", "How I Met Your Mother", "Grey's Anatomy",
        "South Park", "Rick and Morty", "kill two birds with one stone", "the elephant in the room",
        "hold your horses", "on thin ice", "a wolf in sheep's clothing", "the early bird gets the worm",
        "money doesn't grow on trees", "an apple a day keeps the doctor away", "back to square one", "cut corners",
        "add fuel to the fire", "hit the nail on the head", "put all your eggs in one basket", "pull someone's leg",
        "see eye to eye", "as cool as a cucumber", "raining on your parade", "curiosity killed the cat",
        "every cloud has a silver lining", "actions speak louder than words", "you can't judge a book by its cover", "the calm before the storm",
        "a needle in a haystack", "the Eiffel Tower", "the Statue of Liberty", "the Great Wall of China",
        "the Pyramids", "the Leaning Tower of Pisa", "Big Ben", "the Colosseum",
        "Mount Everest", "the Grand Canyon", "Niagara Falls", "Stonehenge",
        "the Golden Gate Bridge", "Times Square", "Disneyland", "the Sydney Opera House",
        "the Taj Mahal", "Hollywood", "Las Vegas", "Venice",
        "the Amazon rainforest", "the Sahara Desert", "the North Pole", "police officer",
        "chef", "lifeguard", "farmer", "pilot",
        "photographer", "detective", "lawyer", "dentist",
        "mail carrier", "DJ", "the Super Bowl", "the World Cup",
        "the Olympics", "the Tour de France", "a marathon", "skydiving",
        "bungee jumping", "surfing", "skiing", "scuba diving",
        "rock climbing", "karaoke", "online shopping", "food delivery",
        "video call", "taking a selfie", "going viral", "The Godfather",
        "The Shawshank Redemption", "Pulp Fiction", "Fight Club", "Inception",
        "Interstellar", "The Truman Show", "Groundhog Day", "The Devil Wears Prada",
        "La La Land", "Bohemian Rhapsody", "Mamma Mia!", "The Sound of Music",
        "Gone with the Wind", "Casablanca", "Parasite", "Get Out",
        "Knives Out", "Catch Me If You Can", "The Green Mile", "Rain Man",
        "Good Will Hunting", "The Da Vinci Code", "Robinson Crusoe", "Around the World in 80 Days",
        "Your Name", "Attack on Titan", "Death Note", "Dragon Ball",
        "One Piece", "Naruto", "Spirited Away", "My Neighbor Totoro",
        "Demon Slayer", "Moby Dick", "Treasure Island", "The Old Man and the Sea",
        "Pride and Prejudice", "Romeo and Juliet", "A Christmas Carol", "Oliver Twist",
        "The Great Gatsby", "Animal Farm", "Don Quixote", "The Odyssey",
        "Frankenstein", "Dracula", "Let It Be", "Yesterday",
        "Imagine", "Thriller", "Billie Jean", "Hotel California",
        "Old Town Road", "Rocket Man", "Yellow Submarine", "Dancing Queen",
        "Singin' in the Rain", "Napoleon", "Shakespeare", "Marie Curie",
        "Elvis Presley", "Michael Jackson", "Beethoven", "Mozart",
        "Vincent van Gogh", "Pablo Picasso", "Charlie Chaplin", "Abraham Lincoln",
        "Christopher Columbus", "Joan of Arc", "Julius Caesar", "Neil Armstrong",
        "Thomas Edison", "Nikola Tesla", "Muhammad Ali", "Marilyn Monroe",
        "Audrey Hepburn", "Bob Marley", "burning the midnight oil", "walking on eggshells",
        "don't cry over spilled milk", "a picture is worth a thousand words", "when it rains it pours", "caught red-handed",
        "don't count your chickens before they hatch", "let sleeping dogs lie", "no pain no gain", "out of the blue",
        "speak of the devil", "the best of both worlds", "time is money", "two peas in a pod",
        "a wild goose chase", "bury the hatchet", "cat got your tongue", "fight fire with fire",
        "in the same boat", "rock the boat", "saved by the bell", "sun",
        "moon", "star", "house", "tree",
        "flower", "apple", "banana", "fish",
        "cat", "dog", "rabbit", "bird",
        "egg", "hat", "glasses", "cup",
        "table", "chair", "door", "window",
        "mountain", "cloud", "rain", "balloon",
        "cake", "ice cream cone", "lollipop", "soccer ball",
        "heart", "smiley face", "car", "boat",
        "rocket", "pencil", "book", "clock",
        "ladder", "snail", "crab", "owl",
        "bee", "lighthouse", "windmill", "swing",
        "slide", "Ferris wheel", "hot air balloon", "tent",
        "guitar", "piano", "microphone", "camera",
        "electric fan", "washing machine", "toilet", "toothpaste",
        "taco", "lantern", "mailbox", "slippers",
        "lamp", "treasure chest", "telescope", "brushing teeth",
        "taking a shower", "fishing", "flying a kite", "building a snowman",
        "jump rope", "horseback riding", "archery", "wedding",
        "graduation", "waiting in line", "sleepwalking", "sneezing",
        "daydreaming", "sunburn", "dragon", "alien",
        "zombie", "vacuum cleaner", "sandwich", "Statue of Liberty",
        "Eiffel Tower", "the pyramids", "Golden Gate Bridge", "Mount Rushmore",
        "treadmill", "juggling", "tangled headphones", "blueberry",
        "avocado", "pumpkin", "corn", "carrot",
        "mushroom", "broccoli", "onion", "chili pepper",
        "bread loaf", "croissant", "pretzel", "cookie",
        "candy cane", "popsicle", "coffee cup", "teapot",
        "wine glass", "beer mug", "water bottle", "frying pan",
        "cooking pot", "kettle", "spatula", "whisk",
        "rolling pin", "cutting board", "salt shaker", "can opener",
        "corkscrew", "toaster", "blender", "refrigerator",
        "microwave", "dishwasher", "sink", "faucet",
        "bathtub", "shower head", "mirror", "hairbrush",
        "razor", "soap bar", "towel rack", "laundry basket",
        "clothes hanger", "iron", "sewing machine", "knitting needles",
        "thread spool", "safety pin", "zipper", "shoelace",
        "sneaker", "boot", "high heel", "flip flops",
        "sock", "mitten", "scarf", "beanie",
        "baseball cap", "crown", "tiara", "necklace",
        "ring", "wristwatch", "briefcase", "suitcase",
        "wallet", "purse", "shopping bag", "gift box",
        "ribbon bow", "envelope", "postage stamp", "newspaper",
        "magazine", "notebook", "calendar", "pushpin",
        "paper clip", "stapler", "scissors", "glue stick",
        "crayon", "paintbrush", "paint palette", "easel",
        "canvas", "sketchpad", "ruler", "protractor",
        "compass", "calculator", "abacus", "globe",
        "map", "flag", "signpost", "traffic cone",
        "fire hydrant", "street sign", "bus stop", "park bench",
        "picnic table", "trash can", "street lamp", "fence",
        "gate", "chimney", "roof", "staircase",
        "elevator", "window shutter", "curtain", "door handle",
        "key", "padlock", "chain", "rope",
        "anchor", "ship wheel", "sail", "oar",
        "life raft", "buoy", "fishing rod", "fishing net",
        "bait bucket", "tackle box", "diving mask", "oxygen tank",
        "surfboard", "snowboard", "ski poles", "ice skates",
        "roller skates", "scooter", "tricycle", "wheelbarrow",
        "lawn mower", "garden hose", "watering can", "flower pot",
        "seed packet", "rake", "shovel", "pitchfork",
        "axe", "hammer", "screwdriver", "wrench",
        "pliers", "nail", "screw", "toolbox",
        "paint roller", "tape measure", "level", "drill",
        "saw", "workbench", "sandpaper", "candlestick",
        "oil lamp", "torch", "matchbox", "sleeping bag",
        "canteen", "binoculars", "walkie talkie", "first aid kit",
        "stethoscope", "syringe", "thermometer", "pill bottle",
        "crutches", "wheelchair", "eyeglasses", "hearing aid",
        "dentures", "coin", "banknote", "credit card",
        "cash register", "vending machine", "shopping cart", "barcode",
        "gift card", "telephone", "rotary phone", "television",
        "radio", "speaker", "turntable", "cassette tape",
        "compact disc", "game controller", "arcade machine", "slot machine",
        "pinball machine", "dice", "playing cards", "chess piece",
        "checkerboard", "dominoes", "jigsaw puzzle", "rubik's cube",
        "yo-yo", "spinning top", "marbles", "kite",
        "paper airplane", "paper boat", "origami crane", "teddy bear",
        "rocking horse", "dollhouse", "building blocks", "toy train",
        "rubber duck", "piggyback ride", "orange", "lemon",
        "mango", "cherry", "grape", "peach",
        "coconut", "potato", "tomato", "garlic",
        "noodles", "rice", "bread", "butter",
        "cheese", "yogurt", "honey", "pancake",
        "waffle", "muffin", "brownie", "candy",
        "caramel", "pudding", "jelly", "oatmeal",
        "cereal", "burrito", "nachos", "lasagna",
        "meatball", "dumpling", "omelette", "bacon",
        "sausage", "steak", "shrimp", "lobster",
        "salmon", "tuna", "oyster", "soup",
        "salad", "pickle", "smoothie", "lemonade",
        "soda", "juice", "green tea", "cocoa",
        "cappuccino", "espresso", "monkey", "donkey",
        "turkey", "tiger", "lion", "zebra",
        "hippo", "rhino", "koala", "camel",
        "llama", "alpaca", "walrus", "seal",
        "otter", "beaver", "badger", "hamster",
        "parrot", "peacock", "pelican", "flamingo",
        "ostrich", "puffin", "seagull", "sparrow",
        "swallow", "woodpecker", "eagle", "falcon",
        "vulture", "dove", "goose", "duckling",
        "piglet", "puppy", "kitten", "bunny",
        "squirrel", "mole", "bat", "frog",
        "toad", "turtle", "tortoise", "lizard",
        "gecko", "iguana", "cobra", "python",
        "crocodile", "whale", "shark", "starfish",
        "seahorse", "spider", "beetle", "ladybug",
        "dragonfly", "grasshopper", "cricket", "mosquito",
        "puppet", "toy car", "skipping rope", "seesaw",
        "sandbox", "snowball", "firework", "candle",
        "pillow", "blanket", "towel", "soap",
        "shampoo", "comb", "spoon", "fork",
        "knife", "plate", "bowl", "bottle",
        "basket", "bucket", "broom", "needle",
        "button", "pocket", "sweater", "jacket",
        "raincoat", "boots", "sandals", "socks",
        "gloves", "bracelet", "earrings", "passport",
        "ticket", "flashlight", "battery", "remote",
        "keyboard", "printer", "stamp", "kitchen",
        "bathroom", "bedroom", "garden", "garage",
        "balcony", "basement", "escalator", "hallway",
        "hospital", "pharmacy", "bakery", "laundry",
        "museum", "theater", "stadium", "playground",
        "aquarium", "zoo", "farm", "forest",
        "desert", "island", "valley", "river",
        "ocean", "mommy", "daddy", "grandma",
        "grandpa", "brother", "sister", "uncle",
        "auntie", "cousin", "neighbor", "nurse",
        "sailor", "soldier", "painter", "singer",
        "dancer", "baker", "barber", "waiter",
        "driver", "guard", "king", "queen",
        "prince", "princess", "wizard", "witch",
        "giant", "ghost", "monster", "angel",
        "fairy",
    ]
}
