import Foundation

// Draw & Guess: concrete, drawable things, stories and titles
enum DrawWordsEN {

    static let pool: [String] = [
        "sun", "moon", "star", "house",
        "tree", "flower", "apple", "banana",
        "fish", "cat", "dog", "rabbit",
        "bird", "egg", "umbrella", "hat",
        "glasses", "cup", "table", "chair",
        "door", "window", "mountain", "cloud",
        "rain", "snowman", "balloon", "cake",
        "ice cream cone", "lollipop", "soccer ball", "heart",
        "smiley face", "car", "boat", "rocket",
        "pencil", "book", "clock", "ladder",
        "giraffe", "elephant", "snail", "butterfly",
        "crab", "octopus", "dinosaur", "penguin",
        "owl", "bee", "lighthouse", "windmill",
        "swing", "slide", "Ferris wheel", "roller coaster",
        "hot air balloon", "tent", "guitar", "piano",
        "microphone", "headphones", "camera", "electric fan",
        "washing machine", "toilet", "toothpaste", "hamburger",
        "french fries", "pizza", "sushi", "taco",
        "lantern", "campfire", "mailbox", "slippers",
        "lamp", "alarm clock", "treasure chest", "telescope",
        "brushing teeth", "taking a shower", "fishing", "flying a kite",
        "building a snowman", "jump rope", "tug of war", "horseback riding",
        "archery", "skiing", "surfing", "scuba diving",
        "rock climbing", "bungee jumping", "wedding", "graduation",
        "traffic jam", "waiting in line", "taking a selfie", "sleepwalking",
        "sneezing", "daydreaming", "sunburn", "mermaid",
        "dragon", "unicorn", "alien", "zombie",
        "vacuum cleaner", "sandwich", "Statue of Liberty", "Eiffel Tower",
        "the pyramids", "Big Ben", "Golden Gate Bridge", "Mount Rushmore",
        "treadmill", "juggling", "walking the dog", "tangled headphones",
        "pineapple", "strawberry", "blueberry", "avocado",
        "pumpkin", "corn", "carrot", "mushroom",
        "broccoli", "onion", "chili pepper", "bread loaf",
        "croissant", "pretzel", "donut", "cupcake",
        "cookie", "candy cane", "popsicle", "milkshake",
        "coffee cup", "teapot", "wine glass", "beer mug",
        "water bottle", "frying pan", "cooking pot", "kettle",
        "spatula", "whisk", "rolling pin", "cutting board",
        "salt shaker", "can opener", "corkscrew", "toaster",
        "blender", "refrigerator", "microwave", "dishwasher",
        "sink", "faucet", "bathtub", "shower head",
        "mirror", "hairbrush", "razor", "soap bar",
        "towel rack", "laundry basket", "clothes hanger", "iron",
        "sewing machine", "knitting needles", "thread spool", "safety pin",
        "zipper", "shoelace", "sneaker", "boot",
        "high heel", "flip flops", "sock", "mitten",
        "scarf", "beanie", "baseball cap", "crown",
        "tiara", "necklace", "ring", "wristwatch",
        "sunglasses", "briefcase", "suitcase", "wallet",
        "purse", "shopping bag", "gift box", "ribbon bow",
        "envelope", "postage stamp", "postcard", "newspaper",
        "magazine", "notebook", "calendar", "pushpin",
        "paper clip", "stapler", "scissors", "glue stick",
        "crayon", "paintbrush", "paint palette", "easel",
        "canvas", "sketchpad", "ruler", "protractor",
        "compass", "calculator", "abacus", "globe",
        "map", "flag", "signpost", "traffic cone",
        "fire hydrant", "street sign", "bus stop", "park bench",
        "picnic table", "trash can", "street lamp", "fence",
        "gate", "chimney", "roof", "staircase",
        "elevator", "window shutter", "curtain", "door handle",
        "key", "padlock", "chain", "rope",
        "anchor", "ship wheel", "sail", "oar",
        "life raft", "buoy", "fishing rod", "fishing net",
        "bait bucket", "tackle box", "diving mask", "oxygen tank",
        "surfboard", "snowboard", "ski poles", "ice skates",
        "roller skates", "skateboard", "scooter", "tricycle",
        "wheelbarrow", "lawn mower", "garden hose", "watering can",
        "flower pot", "seed packet", "rake", "shovel",
        "pitchfork", "axe", "hammer", "screwdriver",
        "wrench", "pliers", "nail", "screw",
        "toolbox", "paint roller", "tape measure", "level",
        "drill", "saw", "workbench", "sandpaper",
        "candlestick", "oil lamp", "torch", "matchbox",
        "sleeping bag", "backpack", "canteen", "binoculars",
        "walkie talkie", "first aid kit", "stethoscope", "syringe",
        "thermometer", "pill bottle", "crutches", "wheelchair",
        "eyeglasses", "hearing aid", "dentures", "piggy bank",
        "coin", "banknote", "credit card", "cash register",
        "vending machine", "shopping cart", "barcode", "receipt",
        "gift card", "telephone", "rotary phone", "television",
        "radio", "speaker", "turntable", "cassette tape",
        "compact disc", "game controller", "arcade machine", "slot machine",
        "pinball machine", "dice", "playing cards", "chess piece",
        "checkerboard", "dominoes", "jigsaw puzzle", "rubik's cube",
        "yo-yo", "spinning top", "marbles", "kite",
        "paper airplane", "paper boat", "origami crane", "teddy bear",
        "rocking horse", "dollhouse", "building blocks", "toy train",
        "rubber duck", "piggyback ride", "orange", "lemon",
        "mango", "cherry", "grape", "peach",
        "coconut", "potato", "tomato", "garlic",
        "noodles", "rice", "bread", "butter",
        "cheese", "yogurt", "honey", "pancake",
        "waffle", "muffin", "brownie", "candy",
        "caramel", "pudding", "jelly", "oatmeal",
        "cereal", "burrito", "nachos", "lasagna",
        "meatball", "dumpling", "omelette", "bacon",
        "sausage", "steak", "shrimp", "lobster",
        "salmon", "tuna", "oyster", "soup",
        "salad", "pickle", "smoothie", "lemonade",
        "soda", "juice", "green tea", "cocoa",
        "cappuccino", "espresso", "monkey", "donkey",
        "turkey", "tiger", "lion", "zebra",
        "hippo", "rhino", "panda", "koala",
        "camel", "llama", "alpaca", "walrus",
        "seal", "otter", "beaver", "badger",
        "hamster", "parrot", "peacock", "pelican",
        "flamingo", "ostrich", "puffin", "seagull",
        "sparrow", "swallow", "woodpecker", "eagle",
        "falcon", "vulture", "dove", "goose",
        "duckling", "piglet", "puppy", "kitten",
        "bunny", "squirrel", "hedgehog", "mole",
        "bat", "frog", "toad", "turtle",
        "tortoise", "lizard", "gecko", "iguana",
        "cobra", "python", "crocodile", "dolphin",
        "whale", "shark", "starfish", "seahorse",
        "spider", "beetle", "ladybug", "dragonfly",
        "grasshopper", "cricket", "mosquito", "puppet",
        "toy car", "skipping rope", "seesaw", "sandbox",
        "snowball", "firework", "candle", "pillow",
        "blanket", "towel", "soap", "shampoo",
        "comb", "spoon", "fork", "knife",
        "plate", "bowl", "bottle", "basket",
        "bucket", "broom", "needle", "button",
        "pocket", "sweater", "jacket", "raincoat",
        "boots", "sandals", "socks", "gloves",
        "bracelet", "earrings", "passport", "ticket",
        "flashlight", "battery", "remote", "keyboard",
        "printer", "stamp", "kitchen", "bathroom",
        "bedroom", "garden", "garage", "balcony",
        "basement", "escalator", "hallway", "hospital",
        "pharmacy", "bakery", "laundry", "museum",
        "theater", "stadium", "playground", "aquarium",
        "zoo", "farm", "forest", "desert",
        "island", "valley", "river", "ocean",
        "The Lion King", "Frozen", "Toy Story", "Finding Nemo",
        "Snow White", "Cinderella", "The Little Mermaid", "Sleeping Beauty",
        "Peter Pan", "Shrek", "Kung Fu Panda", "Ice Age",
        "Minions", "Zootopia", "Cars", "Spider-Man",
        "Batman", "Superman", "Iron Man", "Titanic",
        "Aladdin", "Mulan", "Moana", "Tangled",
        "Bambi", "Dumbo", "Pinocchio", "101 Dalmatians",
        "The Jungle Book", "Madagascar", "Happy Feet", "Rio",
        "Big Hero 6", "Wreck-It Ralph", "Alice in Wonderland", "The Croods",
        "Trolls", "Sing", "Turning Red", "Luca",
        "Soul", "The Grinch", "Home Alone", "SpongeBob",
        "Tom and Jerry", "Mickey Mouse", "Pikachu", "Santa Claus",
        "Winnie the Pooh", "Scooby-Doo", "Bugs Bunny", "Popeye",
        "Garfield", "Snoopy", "The Simpsons", "Hello Kitty",
        "Barbie", "Mario", "Sonic the Hedgehog", "Donkey Kong",
        "Pac-Man", "Angry Birds", "Minecraft", "Doraemon",
        "Astro Boy", "Godzilla", "King Kong", "Frosty the Snowman",
        "The Three Little Pigs", "Little Red Riding Hood", "The Ugly Duckling", "Jack and the Beanstalk",
        "Hansel and Gretel", "The Boy Who Cried Wolf", "Humpty Dumpty", "The Gingerbread Man",
        "Puss in Boots", "hot dog", "tacos", "spaghetti",
        "pancakes", "popcorn", "ice cream", "birthday cake",
        "watermelon", "fish and chips", "chicken soup", "apple pie",
        "hot chocolate", "coffee", "bacon and eggs", "grilled cheese",
        "corn on the cob", "rainbow", "volcano", "thunderstorm",
        "sunflower", "shooting star", "desert island", "Christmas",
        "Halloween", "Thanksgiving", "New Year's Eve", "Valentine's Day",
        "birthday party", "road trip", "camping", "going to the movies",
        "grocery shopping", "working out", "doing laundry", "beach vacation",
        "Star Wars", "Jurassic Park", "The Avengers", "Harry Potter",
        "The Lord of the Rings", "Avatar", "Back to the Future", "The Matrix",
        "Jaws", "Ghostbusters", "Men in Black", "The Wizard of Oz",
        "Beauty and the Beast", "Up", "Ratatouille", "Monsters, Inc.",
        "Inside Out", "Coco", "Encanto", "The Incredibles",
        "Wall-E", "Despicable Me", "Rocky", "Top Gun",
        "Indiana Jones", "The Mummy", "Mission: Impossible", "The Hunger Games",
        "The Terminator", "Alien", "E.T.", "Jumanji",
        "Forrest Gump", "The Martian", "Black Panther", "Wonder Woman",
        "Friends", "Stranger Things", "Game of Thrones", "Breaking Bad",
        "The Office", "Sherlock", "Family Guy", "Squid Game",
        "Black Mirror", "The Walking Dead", "Doctor Who", "The Crown",
        "The Mandalorian", "Wednesday", "Grey's Anatomy", "South Park",
        "Rick and Morty", "spill the beans", "once in a blue moon", "hold your horses",
        "on thin ice", "break a leg", "cost an arm and a leg", "the tip of the iceberg",
        "cut corners", "add fuel to the fire", "beat around the bush", "throw in the towel",
        "pull someone's leg", "as cool as a cucumber", "raining on your parade", "a needle in a haystack",
        "the Eiffel Tower", "the Statue of Liberty", "the Pyramids", "the Colosseum",
        "Mount Everest", "the Grand Canyon", "Niagara Falls", "Stonehenge",
        "the Golden Gate Bridge", "Times Square", "Disneyland", "the Sydney Opera House",
        "the Taj Mahal", "Hollywood", "Las Vegas", "Venice",
        "the Amazon rainforest", "the Sahara Desert", "the North Pole", "firefighter",
        "astronaut", "police officer", "chef", "doctor",
        "teacher", "lifeguard", "farmer", "pilot",
        "photographer", "detective", "lawyer", "dentist",
        "mail carrier", "DJ", "the Super Bowl", "the World Cup",
        "the Olympics", "the Tour de France", "a marathon", "skydiving",
        "video call", "The Godfather", "Pulp Fiction", "Fight Club",
        "Inception", "Interstellar", "Groundhog Day", "Bohemian Rhapsody",
        "Mamma Mia!", "Casablanca", "Parasite", "Get Out",
        "Knives Out", "Rain Man", "The Da Vinci Code", "Sherlock Holmes",
        "Robinson Crusoe", "Your Name", "Attack on Titan", "Death Note",
        "Dragon Ball", "One Piece", "Naruto", "Spirited Away",
        "My Neighbor Totoro", "Demon Slayer", "Moby Dick", "Treasure Island",
        "Romeo and Juliet", "A Christmas Carol", "Oliver Twist", "Animal Farm",
        "Don Quixote", "The Odyssey", "Frankenstein", "Dracula",
        "Thriller", "Billie Jean", "Hotel California", "Rocket Man",
        "Yellow Submarine", "Singin' in the Rain", "Albert Einstein", "Isaac Newton",
        "Cleopatra", "Napoleon", "Shakespeare", "Marie Curie",
        "Elvis Presley", "Michael Jackson", "Leonardo da Vinci", "Beethoven",
        "Mozart", "Vincent van Gogh", "Pablo Picasso", "Charlie Chaplin",
        "Abraham Lincoln", "Christopher Columbus", "Joan of Arc", "Julius Caesar",
        "Neil Armstrong", "Thomas Edison", "Nikola Tesla", "Muhammad Ali",
        "Marilyn Monroe", "Audrey Hepburn", "Bob Marley", "walking on eggshells",
        "bite the bullet", "when it rains it pours", "the last straw", "caught red-handed",
        "jump on the bandwagon", "let sleeping dogs lie", "two peas in a pod", "a wild goose chase",
        "bury the hatchet", "cat got your tongue", "fight fire with fire", "in the same boat",
        "rock the boat", "saved by the bell",
    ]
}
