import Foundation

// Emoji Manager: the hardest game, so the smallest pool — only instantly recognizable picks
enum EmojiWordsEN {

    static let pool: [String] = [
        "The Lion King", "Frozen", "Toy Story", "Finding Nemo",
        "Snow White", "Cinderella", "The Little Mermaid", "Sleeping Beauty",
        "Peter Pan", "Shrek", "Kung Fu Panda", "Ice Age",
        "Minions", "Zootopia", "Cars", "Spider-Man",
        "Batman", "Superman", "Iron Man", "Titanic",
        "Aladdin", "Mulan", "Moana", "Tangled",
        "Bambi", "Dumbo", "Pinocchio", "101 Dalmatians",
        "The Jungle Book", "Madagascar", "Happy Feet", "Rio",
        "Big Hero 6", "Wreck-It Ralph", "Alice in Wonderland", "The Croods",
        "Trolls", "Sing", "Turning Red", "Luca",
        "Soul", "The Grinch", "Home Alone", "SpongeBob",
        "Tom and Jerry", "Mickey Mouse", "Pikachu", "Santa Claus",
        "Winnie the Pooh", "Scooby-Doo", "Bugs Bunny", "Popeye",
        "Garfield", "Snoopy", "The Simpsons", "Hello Kitty",
        "Barbie", "Mario", "Sonic the Hedgehog", "Donkey Kong",
        "Pac-Man", "Angry Birds", "Minecraft", "Doraemon",
        "Astro Boy", "Godzilla", "King Kong", "Frosty the Snowman",
        "The Three Little Pigs", "Little Red Riding Hood", "The Ugly Duckling", "The Tortoise and the Hare",
        "Goldilocks and the Three Bears", "Jack and the Beanstalk", "Hansel and Gretel", "The Boy Who Cried Wolf",
        "The Emperor's New Clothes", "Humpty Dumpty", "The Gingerbread Man", "Puss in Boots",
        "raining cats and dogs", "piece of cake", "cold feet", "couch potato",
        "night owl", "break the ice", "when pigs fly", "time flies",
        "over the moon", "hot dog", "bookworm", "copycat",
        "eagle eye", "busy as a bee", "in hot water", "under the weather",
        "head in the clouds", "green thumb", "sweet tooth", "cat nap",
        "big fish", "top dog", "black sheep", "early bird",
        "heart of gold", "hot potato", "snail mail", "lovebirds",
        "fish out of water", "on cloud nine", "sitting duck", "cash cow",
        "pizza", "hamburger", "french fries", "sushi",
        "tacos", "spaghetti", "pancakes", "popcorn",
        "ice cream", "birthday cake", "donut", "cupcake",
        "watermelon", "pineapple", "strawberry", "peanut butter and jelly",
        "fish and chips", "chicken soup", "apple pie", "hot chocolate",
        "coffee", "milkshake", "bacon and eggs", "grilled cheese",
        "corn on the cob", "panda", "giraffe", "penguin",
        "butterfly", "octopus", "unicorn", "dinosaur",
        "hedgehog", "rainbow", "volcano", "snowman",
        "thunderstorm", "sunflower", "shooting star", "desert island",
        "Christmas", "Halloween", "Thanksgiving", "New Year's Eve",
        "Valentine's Day", "birthday party", "road trip", "camping",
        "going to the movies", "grocery shopping", "working out", "walking the dog",
        "doing laundry", "traffic jam", "beach vacation", "Star Wars",
        "Jurassic Park", "Pirates of the Caribbean", "The Avengers", "Harry Potter",
        "The Lord of the Rings", "Avatar", "Back to the Future", "The Matrix",
        "Jaws", "Ghostbusters", "Men in Black", "The Wizard of Oz",
        "Beauty and the Beast", "Up", "Ratatouille", "Monsters, Inc.",
        "Inside Out", "Coco", "Encanto", "The Incredibles",
        "Wall-E", "Despicable Me", "Rocky", "Top Gun",
        "Indiana Jones", "The Mummy", "Mission: Impossible", "The Hunger Games",
        "The Terminator", "Alien", "E.T.", "Jumanji",
        "Forrest Gump", "The Martian", "Black Panther", "Wonder Woman",
        "Friends", "Stranger Things", "Game of Thrones", "Breaking Bad",
        "The Office", "Sherlock", "Family Guy", "Squid Game",
        "Black Mirror", "The Walking Dead", "Doctor Who", "The Crown",
        "The Mandalorian", "Wednesday", "The Big Bang Theory", "How I Met Your Mother",
        "Grey's Anatomy", "South Park", "Rick and Morty", "kill two birds with one stone",
        "spill the beans", "the elephant in the room", "once in a blue moon", "hold your horses",
        "on thin ice", "a wolf in sheep's clothing", "the early bird gets the worm", "money doesn't grow on trees",
        "an apple a day keeps the doctor away", "break a leg", "cost an arm and a leg", "the tip of the iceberg",
        "a blessing in disguise", "back to square one", "cut corners", "add fuel to the fire",
        "beat around the bush", "hit the nail on the head", "put all your eggs in one basket", "throw in the towel",
        "pull someone's leg", "see eye to eye", "as cool as a cucumber", "raining on your parade",
        "curiosity killed the cat", "every cloud has a silver lining", "actions speak louder than words", "you can't judge a book by its cover",
        "the calm before the storm", "a needle in a haystack", "the Eiffel Tower", "the Statue of Liberty",
        "the Great Wall of China", "the Pyramids", "the Leaning Tower of Pisa", "Big Ben",
        "the Colosseum", "Mount Everest", "the Grand Canyon", "Niagara Falls",
        "Stonehenge", "the Golden Gate Bridge", "Times Square", "Disneyland",
        "the Sydney Opera House", "the Taj Mahal", "Hollywood", "Las Vegas",
        "Venice", "the Amazon rainforest", "the Sahara Desert", "the North Pole",
        "firefighter", "astronaut", "police officer", "chef",
        "doctor", "teacher", "lifeguard", "farmer",
        "pilot", "photographer", "detective", "lawyer",
        "dentist", "mail carrier", "DJ", "the Super Bowl",
        "the World Cup", "the Olympics", "the Tour de France", "a marathon",
        "skydiving", "bungee jumping", "surfing", "skiing",
        "scuba diving", "rock climbing", "karaoke", "escape room",
        "online shopping", "food delivery", "binge-watching", "video call",
        "taking a selfie", "going viral", "The Godfather", "The Shawshank Redemption",
        "Pulp Fiction", "Fight Club", "Inception", "Interstellar",
        "The Truman Show", "Groundhog Day", "The Devil Wears Prada", "La La Land",
        "Bohemian Rhapsody", "Mamma Mia!", "The Sound of Music", "Gone with the Wind",
        "Casablanca", "Parasite", "Get Out", "Knives Out",
        "Catch Me If You Can", "The Green Mile", "Rain Man", "Good Will Hunting",
        "The Da Vinci Code", "Sherlock Holmes", "Robinson Crusoe", "Around the World in 80 Days",
        "Your Name", "Attack on Titan", "Death Note", "Dragon Ball",
        "One Piece", "Naruto", "Spirited Away", "My Neighbor Totoro",
        "Demon Slayer", "Moby Dick", "Treasure Island", "The Old Man and the Sea",
        "Pride and Prejudice", "Romeo and Juliet", "A Christmas Carol", "Oliver Twist",
        "The Great Gatsby", "Animal Farm", "Don Quixote", "The Odyssey",
        "Frankenstein", "Dracula", "Let It Be", "Yesterday",
        "Imagine", "Thriller", "Billie Jean", "Hotel California",
        "Old Town Road", "Rocket Man", "Yellow Submarine", "Dancing Queen",
        "Singin' in the Rain", "Albert Einstein", "Isaac Newton", "Cleopatra",
        "Napoleon", "Shakespeare", "Marie Curie", "Elvis Presley",
        "Michael Jackson", "Leonardo da Vinci", "Beethoven", "Mozart",
        "Vincent van Gogh", "Pablo Picasso", "Charlie Chaplin", "Abraham Lincoln",
        "Christopher Columbus", "Joan of Arc", "Julius Caesar", "Neil Armstrong",
        "Thomas Edison", "Nikola Tesla", "Muhammad Ali", "Marilyn Monroe",
        "Audrey Hepburn", "Bob Marley", "burning the midnight oil", "walking on eggshells",
        "the ball is in your court", "don't cry over spilled milk", "a picture is worth a thousand words", "bite the bullet",
        "let the cat out of the bag", "barking up the wrong tree", "when it rains it pours", "the last straw",
        "caught red-handed", "don't count your chickens before they hatch", "go the extra mile", "jump on the bandwagon",
        "let sleeping dogs lie", "no pain no gain", "out of the blue", "speak of the devil",
        "the best of both worlds", "time is money", "two peas in a pod", "a wild goose chase",
        "bury the hatchet", "cat got your tongue", "fight fire with fire", "in the same boat",
        "rock the boat", "saved by the bell",
    ]
}
