import Foundation

// Lip Reading: short words and phrases with big, distinct mouth shapes
enum LipWordsEN {

    static let pool: [String] = [
        "hello", "goodbye", "thank you", "pizza",
        "banana", "watermelon", "good morning", "I love you",
        "happy birthday", "cheeseburger", "bubble gum", "papa",
        "mama", "wow", "okay", "no way",
        "let's go", "hot dog", "cookie", "milkshake",
        "rainbow", "elephant", "umbrella", "butterfly",
        "basketball", "sunshine", "movie night", "popcorn",
        "chocolate", "vanilla", "strawberry", "blueberry",
        "peanut butter", "bumblebee", "woof woof", "meow",
        "uh oh", "yummy", "bravo", "high five",
        "see you later", "what's up", "piece of cake", "happy new year",
        "trick or treat", "once upon a time", "home sweet home", "easy peasy",
        "oopsie daisy", "supermarket", "roller coaster", "happily ever after",
        "monkey business", "couch potato", "early bird", "night owl",
        "bookworm", "butterfingers", "copycat", "daydreamer",
        "firecracker", "goosebumps", "hiccups", "jellyfish",
        "kangaroo", "lullaby", "marshmallow", "motorcycle",
        "pineapple", "quarterback", "skyscraper", "tornado",
        "volcano", "waterfall", "xylophone", "yo-yo",
        "zigzag", "bubble bath", "peanut butter jelly", "double trouble",
        "may the force be with you", "houston we have a problem", "to be or not to be", "i'll be back",
        "show me the money", "elementary my dear watson", "mission impossible", "hakuna matata",
        "just keep swimming", "you shall not pass", "toy boat", "unique new york",
        "irish wristwatch", "red leather yellow leather", "she sells seashells", "peter piper",
        "rubber baby buggy", "flash message", "eleven benevolent elephants", "truly rural",
        "good blood bad blood", "greek grapes", "break a leg", "hit the road",
        "spill the beans", "cool as a cucumber", "bite your tongue", "hold your horses",
        "when pigs fly", "the big apple", "brain freeze", "cheese wheel",
        "world wide web", "beach ball", "blue moon", "green thumb",
        "silver spoon", "golden ticket", "whale watching", "wishing well",
        "apple", "orange", "lemon", "mango",
        "cherry", "grape", "peach", "coconut",
        "avocado", "broccoli", "carrot", "potato",
        "tomato", "onion", "garlic", "mushroom",
        "noodles", "rice", "bread", "butter",
        "cheese", "yogurt", "honey", "pancake",
        "waffle", "muffin", "brownie", "cupcake",
        "candy", "caramel", "pudding", "jelly",
        "oatmeal", "cereal", "sandwich", "burrito",
        "nachos", "lasagna", "meatball", "dumpling",
        "omelette", "bacon", "sausage", "steak",
        "shrimp", "lobster", "salmon", "tuna",
        "oyster", "soup", "salad", "pickle",
        "popsicle", "smoothie", "lemonade", "soda",
        "juice", "green tea", "cocoa", "cappuccino",
        "espresso", "monkey", "donkey", "turkey",
        "tiger", "lion", "zebra", "hippo",
        "rhino", "panda", "koala", "camel",
        "llama", "alpaca", "walrus", "seal",
        "otter", "beaver", "badger", "hamster",
        "parrot", "peacock", "pelican", "flamingo",
        "ostrich", "puffin", "seagull", "sparrow",
        "swallow", "woodpecker", "owl", "eagle",
        "falcon", "vulture", "dove", "goose",
        "duckling", "piglet", "puppy", "kitten",
        "bunny", "squirrel", "hedgehog", "mole",
        "bat", "frog", "toad", "turtle",
        "tortoise", "lizard", "gecko", "iguana",
        "cobra", "python", "crocodile", "dolphin",
        "whale", "shark", "starfish", "seahorse",
        "octopus", "crab", "snail", "spider",
        "beetle", "ladybug", "dragonfly", "grasshopper",
        "cricket", "mosquito", "good night", "see you soon",
        "sorry", "please", "you're welcome", "congratulations",
        "good luck", "well done", "awesome", "amazing",
        "beautiful", "wonderful", "terrible", "delicious",
        "hungry", "thirsty", "sleepy", "tired",
        "angry", "happy", "sad", "scared",
        "excited", "nervous", "surprised", "boring",
        "funny", "crazy", "lucky", "silly",
        "sweet", "spicy", "salty", "sour",
        "bitter", "freezing", "sunny", "rainy",
        "cloudy", "windy", "snowy", "foggy",
        "kitchen", "bathroom", "bedroom", "garden",
        "garage", "balcony", "basement", "elevator",
        "escalator", "hallway", "hospital", "pharmacy",
        "bakery", "laundry", "museum", "theater",
        "stadium", "playground", "aquarium", "zoo",
        "farm", "forest", "desert", "island",
        "mountain", "valley", "river", "ocean",
        "jumping", "swimming", "singing", "dancing",
        "cooking", "baking", "painting", "reading",
        "writing", "sleeping", "laughing", "crying",
        "shouting", "whispering", "walking", "climbing",
        "driving", "flying", "sailing", "skating",
        "skiing", "surfing", "camping", "shopping",
        "cleaning", "washing", "knitting", "fishing",
        "mommy", "daddy", "grandma", "grandpa",
        "brother", "sister", "uncle", "auntie",
        "cousin", "neighbor", "teacher", "doctor",
        "nurse", "farmer", "pilot", "sailor",
        "soldier", "painter", "singer", "dancer",
        "baker", "barber", "waiter", "driver",
        "guard", "king", "queen", "prince",
        "princess", "wizard", "witch", "giant",
        "dragon", "ghost", "monster", "angel",
        "fairy", "puppet", "teddy bear", "toy car",
        "jigsaw puzzle", "skipping rope", "kite", "swing",
        "seesaw", "sandbox", "snowball", "firework",
        "lantern", "candle", "mirror", "pillow",
        "blanket", "towel", "soap", "shampoo",
        "comb", "spoon", "fork", "knife",
        "plate", "bowl", "bottle", "basket",
        "bucket", "broom", "hammer", "scissors",
        "needle", "button", "zipper", "pocket",
        "sweater", "jacket", "raincoat", "boots",
        "sandals", "socks", "gloves", "scarf",
        "necklace", "bracelet", "earrings", "wallet",
        "suitcase", "passport", "ticket", "map",
        "compass", "telescope", "binoculars", "flashlight",
        "battery", "remote", "keyboard", "printer",
        "mailbox", "newspaper", "magazine", "notebook",
        "calendar", "envelope", "stamp",
    ]
}
